<div dir='rtl'> NumPy برای آرایه های چند بعدی و ضرب ماتریس بسیار مناسب است.</div>

## نحوه فراخوانی

In [1]:
import numpy as np

## تعریف آرایه

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## بروزرسانی

In [7]:
a

array([1, 2, 3])

In [8]:
a[1] = 3
a

array([1, 3, 3])

## تغییر ابعاد

In [9]:
b = np.arange(10).reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
b.reshape(10,)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## ابعاد آرایه

In [11]:
arr = np.arange(1,10)
arr.ndim

1

In [12]:
arr.shape

(9,)

In [13]:
arr.size

9

## تبدیل لیست به آرایه

In [14]:
list2d = [[1,2,3],[4,5,6]]
arr2d = np.asarray(list2d)
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

## آرایه هایی با مقادیر ثابت

In [15]:
listzeros = np.zeros((3,4), dtype='int32')
listzeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
listones = np.ones((2,2))
listones

array([[1., 1.],
       [1., 1.]])

In [17]:
listfull = np.full((2,3),6)
listfull 

array([[6, 6, 6],
       [6, 6, 6]])

In [18]:
listeye = np.eye(3)
listeye 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.linspace(1, 4, num=4)

array([1., 2., 3., 4.])

In [20]:
rarr = np.random.random((3,4))
rarr

array([[9.70508711e-01, 4.11319690e-01, 9.63338126e-02, 5.78944493e-01],
       [4.00049654e-01, 4.72063065e-01, 9.49547218e-01, 8.66718935e-01],
       [2.43129166e-01, 5.56312817e-01, 5.99719302e-04, 8.48783647e-01]])

## توابع آماده

<h3 dir='rtl'>توابع آماری کتابخانه NumPy</h3>

<div dir='rtl'>

<ul>
<li><code>min</code>:محاسبه کمینه مقادیر </li>
<li><code>max</code>:محاسبه بیشینه مقادیر </li>
<li><code>mean</code>: محاسبه میانگین مقادیر </li>
<li><code>median</code>: محاسبه میانه مقادیر </li>
<li><code>std</code>:محاسبه انحراف معیار مقادیر</li>
</ul>
    
    
</div>

In [21]:
np.argmax(rarr, axis=0)

array([0, 2, 1, 1], dtype=int64)

In [22]:
np.argmin(rarr, axis=1)

array([2, 0, 2], dtype=int64)

## ایندکس ها

In [23]:
rarr

array([[9.70508711e-01, 4.11319690e-01, 9.63338126e-02, 5.78944493e-01],
       [4.00049654e-01, 4.72063065e-01, 9.49547218e-01, 8.66718935e-01],
       [2.43129166e-01, 5.56312817e-01, 5.99719302e-04, 8.48783647e-01]])

In [24]:
rarr[1,2]

0.9495472179720384

In [25]:
rarr[0:2,:]

array([[0.97050871, 0.41131969, 0.09633381, 0.57894449],
       [0.40004965, 0.47206307, 0.94954722, 0.86671894]])

In [26]:
rarr[:,1:]

array([[4.11319690e-01, 9.63338126e-02, 5.78944493e-01],
       [4.72063065e-01, 9.49547218e-01, 8.66718935e-01],
       [5.56312817e-01, 5.99719302e-04, 8.48783647e-01]])

In [27]:
rarr[:-1,:]

array([[0.97050871, 0.41131969, 0.09633381, 0.57894449],
       [0.40004965, 0.47206307, 0.94954722, 0.86671894]])

In [28]:
rarr[:,:-1]

array([[9.70508711e-01, 4.11319690e-01, 9.63338126e-02],
       [4.00049654e-01, 4.72063065e-01, 9.49547218e-01],
       [2.43129166e-01, 5.56312817e-01, 5.99719302e-04]])

## توابع ریاضی

In [29]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [30]:
x

array([[1., 2.],
       [3., 4.]])

In [31]:
y

array([[5., 6.],
       [7., 8.]])

In [32]:
x.T

array([[1., 3.],
       [2., 4.]])

In [33]:
x > 2

array([[False, False],
       [ True,  True]])

In [34]:
x + 1

array([[2., 3.],
       [4., 5.]])

In [35]:
x[x > 2]

array([3., 4.])

In [36]:
x + y

array([[ 6.,  8.],
       [10., 12.]])

In [37]:
10 * np.sin(x)

array([[ 8.41470985,  9.09297427],
       [ 1.41120008, -7.56802495]])

In [38]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [39]:
v = x.flatten()
w = y.flatten()

In [40]:
v

array([1., 2., 3., 4.])

In [41]:
w

array([5., 6., 7., 8.])

In [42]:
v.dot(w)

70.0

In [43]:
np.dot(v, w)

70.0

In [44]:
np.matmul(v, w)

70.0

In [45]:
np.linalg.det(x)

-2.0000000000000004

## ترکیب

In [46]:
x

array([[1., 2.],
       [3., 4.]])

In [47]:
y

array([[5., 6.],
       [7., 8.]])

In [48]:
np.hstack((x, y))

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [49]:
np.vstack((x, y))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])